stages:
  - deploy

variables:
  IMAGE_TAG: "docker.io/ilmannafian/fenn"

fe nightly:
  stage: deploy
  image: docker:20
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE_TAG:fenightly ./fenn-fe
    - docker push $IMAGE_TAG:fenightly
