name: Publish Docker image

on:
  push:
    branches:
      - dev
    tags:
      - v*.*.*

jobs:
  be:
    name: Publish image
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        app: [fe, be]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          context: ./fenn-${{ matrix.app }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ilmannafian/fenn:${{ matrix.app }}nightly
      - name: Add tag to env var with leading v removed
        run: |
          ref="${github_ref/refs\/tags\/v/}"
          echo $ref
          echo "::set-env name=ref::$ref"
        if: github.ref == 'refs/heads/v*.*.*'
        env:
          github_ref: ${{ github.ref }}
      - name: Build and push
        if: github.ref == 'refs/heads/v*.*.*'
        uses: docker/build-push-action@v2
        with:
          context: ./fenn-${{ matrix.app }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ilmannafian/fenn:${{ matrix.app }}$ref
